id = "replicant"
name = "Replicant"
version = "0.0.2"
schema_version = 1
authors = ["Pierre Nel <hello@pierre.io>"]
description = "A port of Kenzie Bottoms' Replicant theme, based on a palette from Bladerunner."
repository = "https://github.com/pierrenel/replicant"
